// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v5.27.1
// source: media_library_service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "media";

export interface SearchMovieByNameRequest {
  name: string;
}

export interface SearchMovieByNameResponse {
  movie: Movie[];
}

export interface Movie {
  id: string;
  title: string;
  overview: string;
  releaseDate: string;
  posterPath: string;
  backdropPath: string;
  popularity: number;
}

export const MEDIA_PACKAGE_NAME = "media";

export interface MediaLibraryServiceClient {
  searchMovieByName(request: SearchMovieByNameRequest): Observable<SearchMovieByNameResponse>;
}

export interface MediaLibraryServiceController {
  searchMovieByName(
    request: SearchMovieByNameRequest,
  ): Promise<SearchMovieByNameResponse> | Observable<SearchMovieByNameResponse> | SearchMovieByNameResponse;
}

export function MediaLibraryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["searchMovieByName"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MediaLibraryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MediaLibraryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MEDIA_LIBRARY_SERVICE_NAME = "MediaLibraryService";
